### ISSUE TITLE
Write features that you can think of

### ISSUE THREAD

**Issue by saeedntt** [xtoolkit/android-chef-assistant#4]
Write as many features as possible

**Comment by nrazavi70** [comment]
Make a slide-down list of groceries to choose from when entering the requirements.

**Comment by nrazavi70** [comment]
Tag different groceries based on different meals they belong to or if they are in a certain diet or not. (Vegan for instance)

**Comment by nrazavi70** [comment]
Ability to set prices for groceries to calculate the cost of groceries per month or to set a budget limit for each month's groceries costs.

**Comment by nrazavi70** [comment]
Alerts for expiry dates and when you run out of a certain mat

**Comment by nrazavi70** [comment]
Ability to group multiple mats so that they can be chosen according to user's preference. (Snack group for instance can contain pretzels, chips, chocolate, etc while Drinks group can contain certain brands of beer or whiskey ...)

**Comment by nrazavi70** [comment]
Being able to calculate calorie of the food.

**Comment by nrazavi70** [comment]
User can enter medical conditions for example heart diseases so they will be alerted when they are buying too much unhealthy oily food

**Comment by nrazavi70** [comment]
Maybe an alert when they are close to a super market to get their groceries
